name: Node.js CI
on: [push]
env:
  NODE_ENV: production
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: 'Node.js 21 installieren'
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      # Variable section
      - name: Echo NODE_ENV
        run: |
          echo $NODE_ENV
          echo ${{ secrets.DOCKERHUB_TOKEN }}
          echo ${{ vars.DOCKERHUB_USERNAME }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
